# Generated by Django 3.2.5 on 2021-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain_blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(null=True)),
                ('hash', models.CharField(max_length=64, null=True)),
                ('timestamp', models.CharField(max_length=80, null=True)),
                ('miner', models.CharField(max_length=80, null=True)),
                ('transactionCount', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
